ARG version 
FROM almalinux:${version:-8}
ARG trainer 
ARG duration 
ARG course
RUN "echo trainer is ${trainer:-kedarnath}, duration is ${duration:-1week}, & course is ${course:-Docker}" 
CMD [ "sleep","100" ]
